name = "auto-reaction-bot"
main = "src/index.js"
compatibility_date = "2024-02-08"

[vars]
BOT_TOKEN = "7901984362:AAEg1vstb7Hw9vqD8gU-sUNyiUPkd2TJoz4"
BOT_USERNAME = "Auto_Reaction_Xrobot"
EMOJI_LIST = "ğŸ‘â¤ğŸ”¥ğŸ¥°ğŸ‘ğŸ˜ğŸ‰ğŸ¤©ğŸ™ğŸ‘ŒğŸ•ŠğŸ˜ğŸ³â¤â€ğŸ”¥ğŸ’¯âš¡ğŸ†"
RANDOM_LEVEL = "0"
RESTRICTED_CHATS = "-1002205076761"
